
# /*******************************************************************
# *
# * Copyright         : 2024/04/18 이현기(Lee Hyungi)
# * File Name         : docker-compose.yml
# * Description       : 해당 파일은 Hadoop EcoSystem의 각 서비스들을 올리기 위해 
#                       필요한 docker-compose.yml 파일입니다.
# *                    
# * Revision History  :
# * Date              Author           Comments
#   2024/04/17  이현기 (Lee Hyungi)     초기 작업 착수
# * ------------------------------------------------------------------
# * 2024/04/17  이현기 (Lee Hyungi)    Zookeeper, Kafka 서비스 작성
# * ------------------------------------------------------------------
# * 2024/04/18  이현기 (Lee Hyungi)    HDFS 서비스 작성
# * ------------------------------------------------------------------
# * 
# /******************************************************************/

version: "3"
services:

# Zookeeper 컨테이너 정의 -- START
  zoo-1:
    image: zookeeper
    restart: always
    hostname: zoo-1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo-1:2888:3888;2181 server.2=zoo-2:2888:3888;2181 server.3=zoo-3:2888:3888;2181

  zoo-2:
    image: zookeeper
    restart: always
    hostname: zoo-2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo-1:2888:3888;2181 server.2=zoo-2:2888:3888;2181 server.3=zoo-3:2888:3888;2181

  zoo-3:
    image: zookeeper
    restart: always
    hostname: zoo-3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo-1:2888:3888;2181 server.2=zoo-2:2888:3888;2181 server.3=zoo-3:2888:3888;2181
# Zookeeper 컨테이너 정의 -- END

# Kafka 컨테이너 정의 -- START
  kafka-1:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-1
    ports:
      - 29092:29092
    depends_on:
      - zoo-1
      - zoo-2
      - zoo-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181,zoo-2:2182,zoo-3:2183
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  kafka-2:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-2
    ports:
      - 39092:39092
    depends_on:
      - zoo-1
      - zoo-2
      - zoo-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181,zoo-2:2182,zoo-3:2183
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  kafka-3:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-3
    ports:
      - 49092:49092
    depends_on:
      - zoo-1
      - zoo-2
      - zoo-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181,zoo-2:2182,zoo-3:2183
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://localhost:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
# Kafka 컨테이너 정의 -- START

